name: Action tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  schema:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # Strict
          - suite: strict
            schema: ./schema/schema.yaml
            target: ./tests/nostrict/valid/matching-fields.yaml
            no-strict: true
            error-is-success: false
          - suite: strict
            schema: ./schema/schema.yaml
            target: ./tests/nostrict/valid/extra-argument.yaml
            no-strict: true
            error-is-success: false
          - suite: strict
            schema: ./schema/schema.yaml
            target: ./tests/nostrict/invalid/not-a-boolean.yaml
            no-strict: true
            error-is-success: true
          - suite: strict
            schema: ./schema/schema.yaml
            target: ./tests/nostrict/invalid/nums-out-of-range.yaml
            no-strict: true
            error-is-success: true

          # Nostrict
          - suite: nostrict
            schema: ./schema/schema.yaml
            target: ./tests/strict/valid/matching-fields.yaml
            no-strict: false
            error-is-success: false
          - suite: nostrict
            schema: ./schema/schema.yaml
            target: ./tests/strict/invalid/extra-argument.yaml
            no-strict: false
            error-is-success: true

          # Comma separated
          - suite: comma-separated
            schema: ./schema/schema.yaml
            target: tests/nostrict/valid,tests/strict/valid
            no-strict: true
            error-is-success: false
          - suite: comma-separated
            schema: ./schema/schema.yaml
            target: ./tests/nostrict/valid/extra-argument.yaml,./tests/strict/valid/matchin-fields.yaml
            no-strict: true
            error-is-success: false

          # glob pattern
          - suite: glob-pattern
            schema: ./schema/schema.yaml
            path-glob: "./tests/**/valid/*.yaml"

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: ./
      name: "Test: ${{ matrix.test.suite }} ${{ matrix.test.target }}"
      with:
        schema: ${{ matrix.test.schema }}
        target: ${{ matrix.test.target }}
        no-strict: ${{ matrix.test.no-strict }}
        error-is-success: ${{ matrix.test.error-is-success }}
